[theme]
primaryColor = "#333333"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
